name: Python CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        if [[ ${{ matrix.python }} == 2* ]]; then
          pip install -r py2_requirements.txt
        else
          pip install -r py3_requirements.txt
        fi
    - name: Run tests
      run: make test
