name: Python Package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install .
          pip install pytest

      - name: Start Jupyter Notebook
        run: |
          nohup jupyter-notebook --config=./tests/resources/jupyter_server_config.py --NotebookApp.token='secret' &
          sleep 5

      - name: Run tests
        run: pytest -v
