name: Tufuwu/test2
on:
  push:
    branches:
    - "**/*"
  pull_request:
concurrency:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.8'
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: pip install -r requirements.txt
    - run: wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ${{ github.workspace }}/miniconda.sh
    - run: bash ${{ github.workspace }}/miniconda.sh -b -u -p ${{ github.workspace }}/miniconda
    - run: export PATH="${{ github.workspace }}/minicoonda/bin:$PATH"
    - run: hash -r
    - run: pip install nose coverage coveralls flake8 scikit-image
    - run: pip install -e .
    - run: flake8
    - run: nosetests -sv --with-doctest --no-byte-compile --with-coverage --cover-package=tftb
    - run: coveralls
      if: "${{ success() }}"
