name: Python CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install flake8 coveralls rply
      - name: Run tests with coverage
        run: coverage run test.py
      - name: Run flake8
        run: flake8 .
      - name: Upload coverage to coveralls
        run: coveralls
