name: Python Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu: xenial
    strategy:
      matrix:
        python: ["3.8"]
        allow_failures:
          - python: "3.8"
          - python: "3.8"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install tox-travis coveralls
      - name: Run tests
        run: tox
      - name: Upload coverage
        run: coveralls
