name: Python Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        include:
          - python: 3.8
            image: python:3.8
          - python: pypy-3.8
            image: pypy:latest

    steps:
      - uses: actions/checkout@v2
      - run: pip install -r requirements-test.txt
      - run: python -m unittest discover -s tests
      - run: coverage run run_tests.py && coverage report -m

notifications:
  email: false
