name: Python package

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, pypy-3.8]
        test-suite: ['adddelete', 'compartmentedmodel', 'networkdynamics', 'sir', 'sirs', 'sir_fixedrecovery', 'sis', 'sis_fixedrecovery', 'seir', 'stochasticrates', 'monitor', 'generators', 'loci', 'adddelete', 'percolate']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coveralls
    - name: Test with coverage
      run: |
        coverage run --include './epydemic/*' -m nose test/test_${{ matrix.test-suite }}.py
    - name: Report coverage to coveralls
      run: coveralls
