name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install graphviz
      run: sudo apt-get install graphviz

    - name: Install dependencies
      run: pip install .[test] codecov

    - name: Run tests
      run: ./run-tests.py

    # after_success: codecov is not directly supported in Github Actions. You can use a workaround by using a step to upload the coverage report to codecov.
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)

