name: Tufuwu/test2
on:
  push:
    branches:
    - "**/*"
  pull_request:
concurrency:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: "${{ matrix.python }}"
    - name: Set up pip cache
      uses: actions/cache@v3.3.2
      with:
        path: "~/.cache/pip"
        key: "${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}"
        restore-keys: "${{ runner.os }}-pip-"
    - run: git config --global user.name "Git Cola"
    - run: git config --global user.email git-cola@localhost.localdomain
    - run: sudo apt update
    - run: sudo apt install -y gettext
    - run: sudo apt install -y rsync
    - run: sudo apt install -y python-sphinx
    - run: sudo apt install -y python3-sphinx
    - run: sudo apt install -y python-pyqt5
    - run: sudo apt install -y python3-pyqt5
    - run: sudo apt install -y python3-venv
    - run: make all
    - run: pip install tox tox-venv
    - run: tox
    - run: tox -e pylint
    strategy:
      matrix:
        python:
        - 3.8
        - 3.9
