name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetch all history for SonarCloud analysis

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'oracle'

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: bash scripts/install.sh

    - name: Run tests
      run: bash scripts/run_tests.sh

    - name: SonarCloud Scan
      if: github.event_name == 'push' && github.event.pull_request == null
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
          -Dsonar.organization=jonlabelle-github \
          -Dsonar.projectKey=your_project_key

    - name: Cache SonarCloud
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-cache
        restore-keys: |
          ${{ runner.os }}-sonar-cache

  notifications:
    email:
      on_success: never
      on_failure: always
