name: Python CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.9"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: $HOME/.cache/pip
        key: ${{ matrix.python }}-pip
        restore-keys: |
          ${{ matrix.python }}-pip
    - name: Install dependencies
      run: |
        pip install tox-travis
        pip install coveralls
        pip install -r requirements/testing.txt
    - name: Lint with flake8
      run: flake8
    - name: Run tests
      run: tox
    - name: Report coverage
      run: coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
