name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip and setuptools
        run: |
          pip install -U --force setuptools pip

      - name: Install package
        run: |
          python setup.py develop
          pip install -e '.[tests]'

      - name: Run pylama
        run: pylama

      - name: Run tests
        run: py.test
