name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.8]
        include:
          - python-version: 3.8
            ipython-version: '7.9'
            pandas-version: '0.24.2'
          - python-version: 3.8
            ipython-version: '7'
            pandas-version: '1'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install IPython==${{ matrix.ipython-version }}
        pip install pandas==${{ matrix.pandas-version }}
        pip install .[test]
    - name: Test with pytest
      run: |
        python -c 'import pytorch_memlab'
        pytest test/test_mem_reporter.py

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    if: github.event_name == 'release'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install IPython==7
        pip install pandas==1
        pip install .[test]
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: yoursky
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pip install twine
        python setup.py sdist bdist_wheel
        twine upload dist/*

